### ISSUE TITLE
Default login credentials

### ISSUE THREAD

**Issue by Nick-Triller** [anthonynsimon/parrot#32]
What are the default login credentials?

Thanks in advance!

**Comment by anthonynsimon** [comment]
Hi! What login credentials are you referring to? The web-app comes without any default account/data, you just create one by registering on the landing page (or going directly to it: `https://localhost/register`). Let me know if that's what you meant :)

**Comment by Nick-Triller** [comment]
Thank you for the swift response! Yes, I was referring to web-app login credentials.

Registering resulted in the following error message on the register page: "Something went wrong. That's all we know." I wrongly assumed the reason was that sending a registration confirmation email failed because I don't have a SMTP server on the server parrot runs on. 

The reason the registration failed is that the web client POSTS to https://localhost/api/v1/users/register, but parrot runs in a virtual machine in docker (dedicated IP instead of localhost).

**Comment by Nick-Triller** [comment]
Being able to configure the backend address when building the frontend would make sense. Excuse my ignorance if this is already possible, I haven't looked at the code yet.

**Comment by anthonynsimon** [comment]
Hey, yes you are correct, this last part was not implemented.

I just implemented basic functionality for this, as well as some usage info. I just realized that this wasn't there yet, and there was no docs for it, so thanks for pointing it out :)

Anyways, now you can print some usage info by turning the `-h` or `--help` flag on any of the two setup scripts:

```bash
$ ./scripts/buildweb.sh --help
buildweb installs depenencies and builds the web app for Parrot.

Usage:
	./buildweb.sh [flag] [value]

The flags are:

	-api | --api-address	the address where the Parrot API is localed.
	Example: ./buildweb.sh -api http://localhost:8080
```

So to set the API address when building the web app, simply use something like: `./scripts/buildweb.sh -api https://192.168.0.1/v1/api` for example.

Hope it helps, let me know if anything!

**Comment by Nick-Triller** [comment]
The `--help` and `--api-address` options work as advertised. Great!

I am studying golang at the moment. I will make sure to contribute once I am comfortable with the language :)

**Comment by anthonynsimon** [comment]
Sure, any kind of contribution is more than welcome!

**Comment by csbenz** [comment]
I'm still getting "Something went wrong. That's all we know." Message and no output in the log on the server side. I'm using Ubuntu 16.04 on Digital Ocean and tried setting './scripts/buildweb.sh -api https://192.168.0.1/v1/api' to my IP.
Do you know what I'm doing wrong?

**Comment by anthonynsimon** [comment]
Hi @csbenz , the `-api` flag expects only the host (and port) at which the API server is listening to, not the entire path. So for example, if your API server is listening over HTTPS at `https://localhost`, you should use:

```bash
./scripts/buildweb.sh -api https://localhost
```

You can test that the API server is already up and running by sending a GET request to `https://localhost/api/v1/ping`, assuming that the server's host address is `https://localhost`

Let me know if that helps.

**Comment by csbenz** [comment]
HI @anthonynsimon, thanks for your help.
I changed to what you said, using `./scripts/buildweb.sh -api https://xx.xx.xx.xx` with my server's address. The ping test works, I see the message in the browser and on the server's log output. But when I try to register I get the same message "Something went wrong. That's all we know.".

**Comment by anthonynsimon** [comment]
@csbenz could you check out the developer console in the browser when trying to register and see if you get any specific error there?

BTW, are you using the deployment script via docker or deployed on your own?

**Comment by csbenz** [comment]
@anthonynsimon I hadn't thought about that. I'm getting th following error:
```
XMLHttpRequest cannot load https://xxxxxxxxxx/users/register. Response to preflight request doesn't
pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'https://xxxxxxxxx' is therefore not allowed access. The response had HTTP status code
405
```

**Comment by csbenz** [comment]
Sorry I was accessing from a wrong url, because I have two domain names pointing to the same IP. Please ignore the above error. My browser's console output is now:

````
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at e.t.json (vendor.06941a3….bundle.js:1368)
    at e.selector (main.de85a04….bundle.js:1)
    at e.error (vendor.06941a3….bundle.js:990)
    at e._error (vendor.06941a3….bundle.js:50)
    at e.error (vendor.06941a3….bundle.js:50)
    at XMLHttpRequest.f (vendor.06941a3….bundle.js:1361)
    at t.invokeTask (vendor.06941a3….bundle.js:2090)
    at Object.onInvokeTask (vendor.06941a3….bundle.js:554)
    at t.invokeTask (vendor.06941a3….bundle.js:2090)
    at n.runTask (vendor.06941a3….bundle.js:2090)
    at XMLHttpRequest.invoke (vendor.06941a3….bundle.js:2090)
```

**Comment by anthonynsimon** [comment]
@csbenz oh ok it looks like CORS is not enabled, at the moment this is handled by NGINX which is the reverse proxy that docker launches and puts infront of the API server.

I'm not really sure what could be going on in there, I just tried it over here and it's working fine :/ Is the address that you are using when building the web app the API server itself or the reverse-proxy?

**Comment by anthonynsimon** [comment]
@csbenz ok no worries.

I've never seen that last error before during development, could you check the json document being received on the developer tools from your browser? It looks like it might be receiving non-json data

**Comment by anthonynsimon** [comment]
The error message says that the first token is `<`, which gives me the impression that the document received is somehow HTMl/XML. Possibly some Not Found page returned by the server?

**Comment by csbenz** [comment]
@anthonynsimon Hmm I'm getting thw following response:
```
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by anthonynsimon** [comment]
@csbenz ok after digging a bit further, I think I got it. If you specify a custom URL when building the web app it should include the full API path, as in `./scripts/buildweb.sh -api https://localhost/api/v1`, I was mistaken about it, the script doesn't resolve the actual path by itself, sorry about that.

Let me know if that works.

**Comment by csbenz** [comment]
@anthonynsimon Thanks!! It worked :) FYI in your first comment on this issue, you inverted `api/v1` with `v1/api`. Thank you for your time!

**Comment by anthonynsimon** [comment]
Thanks for pointing that out! I'll fix it and double check the docs too.
